export let produits = [
  {
    id: 1,
    libelle: 'Laptop Pro 15"',
    prix: 1299.99,
    stock: 15,
    categorie: "Informatique",
  },
  {
    id: 2,
    libelle: 'Laptop Ultrabook 13"',
    prix: 999.99,
    stock: 10,
    categorie: "Informatique",
  },
  {
    id: 3,
    libelle: "PC Fixe Gaming",
    prix: 1799.99,
    stock: 8,
    categorie: "Informatique",
  },
  {
    id: 4,
    libelle: 'Tablette 10"',
    prix: 349.99,
    stock: 25,
    categorie: "Informatique",
  },
  {
    id: 5,
    libelle: "Mac Mini M2",
    prix: 699.99,
    stock: 12,
    categorie: "Informatique",
  },

  {
    id: 6,
    libelle: "Souris sans fil",
    prix: 29.99,
    stock: 50,
    categorie: "Accessoires",
  },
  {
    id: 7,
    libelle: "Clavier mécanique",
    prix: 89.99,
    stock: 30,
    categorie: "Accessoires",
  },
  {
    id: 8,
    libelle: "Webcam HD 1080p",
    prix: 59.99,
    stock: 40,
    categorie: "Accessoires",
  },
  {
    id: 9,
    libelle: "Hub USB-C 7 ports",
    prix: 39.99,
    stock: 35,
    categorie: "Accessoires",
  },
  {
    id: 10,
    libelle: "Tapis de souris XXL",
    prix: 19.99,
    stock: 60,
    categorie: "Accessoires",
  },
  {
    id: 11,
    libelle: "Support laptop réglable",
    prix: 34.99,
    stock: 45,
    categorie: "Accessoires",
  },
  {
    id: 12,
    libelle: "Câble HDMI 2m",
    prix: 9.99,
    stock: 80,
    categorie: "Accessoires",
  },

  {
    id: 13,
    libelle: 'Écran 27" 4K',
    prix: 449.99,
    stock: 18,
    categorie: "Écrans",
  },
  {
    id: 14,
    libelle: 'Écran 24" Full HD',
    prix: 199.99,
    stock: 22,
    categorie: "Écrans",
  },
  {
    id: 15,
    libelle: "Écran gaming 144Hz",
    prix: 329.99,
    stock: 14,
    categorie: "Écrans",
  },
  {
    id: 16,
    libelle: 'Écran ultra-wide 34"',
    prix: 599.99,
    stock: 7,
    categorie: "Écrans",
  },

  {
    id: 17,
    libelle: "Casque Bluetooth ANC",
    prix: 149.99,
    stock: 28,
    categorie: "Audio",
  },
  {
    id: 18,
    libelle: "Écouteurs intra-auriculaires",
    prix: 79.99,
    stock: 40,
    categorie: "Audio",
  },
  {
    id: 19,
    libelle: "Enceinte portable Bluetooth",
    prix: 59.99,
    stock: 33,
    categorie: "Audio",
  },
  {
    id: 20,
    libelle: "Microphone USB cardioïde",
    prix: 99.99,
    stock: 20,
    categorie: "Audio",
  },
  {
    id: 21,
    libelle: "Carte son externe",
    prix: 49.99,
    stock: 15,
    categorie: "Audio",
  },

  {
    id: 22,
    libelle: "SSD 1To NVMe",
    prix: 89.99,
    stock: 55,
    categorie: "Stockage",
  },
  {
    id: 23,
    libelle: "SSD 500Go SATA",
    prix: 49.99,
    stock: 60,
    categorie: "Stockage",
  },
  {
    id: 24,
    libelle: "Disque dur externe 2To",
    prix: 69.99,
    stock: 38,
    categorie: "Stockage",
  },
  {
    id: 25,
    libelle: "Clé USB 128Go",
    prix: 14.99,
    stock: 90,
    categorie: "Stockage",
  },
  {
    id: 26,
    libelle: "Carte mémoire 64Go",
    prix: 12.99,
    stock: 75,
    categorie: "Stockage",
  },

  {
    id: 27,
    libelle: "Chargeur rapide 65W",
    prix: 24.99,
    stock: 50,
    categorie: "Énergie",
  },
  {
    id: 28,
    libelle: "Batterie externe 20000mAh",
    prix: 39.99,
    stock: 42,
    categorie: "Énergie",
  },
  {
    id: 29,
    libelle: "Multiprise parafoudre",
    prix: 29.99,
    stock: 35,
    categorie: "Énergie",
  },
  {
    id: 30,
    libelle: "Onduleur 600VA",
    prix: 79.99,
    stock: 10,
    categorie: "Énergie",
  },

  {
    id: 31,
    libelle: "Imprimante laser mono",
    prix: 179.99,
    stock: 12,
    categorie: "Impression",
  },
  {
    id: 32,
    libelle: "Imprimante jet d'encre",
    prix: 99.99,
    stock: 18,
    categorie: "Impression",
  },
  {
    id: 33,
    libelle: "Scanner A4 portable",
    prix: 129.99,
    stock: 9,
    categorie: "Impression",
  },
];
